<a href="https://colab.research.google.com/github/Vidushi2601/CipherSchools-DataSci-ML-Hybrid/blob/main/Cipher_lecture_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Manipulation and Analysis with NuMPY

In [3]:
pip install numpy

In [2]:
import numpy as np
#creating 1d array from a list
arr1=np.array([1,2,3,4,5])
print(arr1)

#Creating 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [4]:
#Creating arrays with functions


#Creating an array of zeros
zeros=np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#creating an array of ones
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#create array with a range of values
range_arr=np.arange(10,20,2)
print(range_arr)

[10 12 14 16 18]


In [7]:
#Creating an array with random values
random_arr=np.random.rand(3,3)
print(random_arr)

[[0.63625328 0.44403302 0.8628658 ]
 [0.77936323 0.96503883 0.04339425]
 [0.84946782 0.7507987  0.71005815]]


Basic Array operations- Element wise operations

In [8]:
arr=np.array([1,2,3,4,5])
#Element wise addition
print(arr+2)

[3 4 5 6 7]


In [9]:
#Element wise multiplication
print(arr*2)

[ 2  4  6  8 10]


In [10]:
#Element wise subtraction
print(arr-1)

[0 1 2 3 4]


In [11]:
#Element wise division
print(arr/2)

[0.5 1.  1.5 2.  2.5]


Mathematical operations

In [12]:
#Square root
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [13]:
#Exponential
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [14]:
#Logarithm
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [15]:
#sine
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


Indexing

In [16]:
#Slicing array
print(arr[1:4])
print(arr[:3])

[2 3 4]
[1 2 3]


In [17]:
#Boolean Indexing
print(arr[arr>3])

[4 5]


In [19]:
#Fancy Indexing
Indices=[0,2,4]
print(arr[Indices])

[1 3 5]


Reshaping and Transposing


In [20]:
arr=np.array([[1,2,3],[4,5,6]])
#Reshaping the array
reshaped=arr.reshape((3,2))
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
transposed=arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


Aggregate functions- Sum  and  Mean

In [22]:
#Sum of all elements
print(np.sum(arr))

21


In [23]:
#sum along columns
print(np.sum(arr,axis=0))

[5 7 9]


In [24]:
#sum along rows
print(np.sum(arr,axis=1))

[ 6 15]


In [25]:
#mean of all elements
print(np.mean(arr))

3.5


Min and Max

In [26]:
#Minimum value
print(np.min(arr))

1


In [27]:
print(np.max(arr))

6


In [28]:
#index of min value
print(np.argmin(arr))

0


In [29]:
#index of max value
print(np.argmax(arr))

5
